 import {Food} from "./app/shared/models/Food";

 export const sample_foods: Food[] =[
    {
        id:"1",
        nom:"Skillet Stuffed Shell",
        ingredients:['coffe','  water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:false,
        image:"assets/i1.png",
    },
    {
        id:"2",
        nom:"Mustard Chicken",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:true,
        image:"assets/i2.png",
    },
    {
        id:"3",
        nom:"Easy Chicken Al Pastor",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:true,
        image:"assets/i3.png",
    },
    {
        id:"4",
        nom:"Galette des Rois",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:false,
        image:"assets/i4.png",
    },
    {
        id:"5",
        nom:"Tiny Pasta Salad",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:true,
        image:"assets/i5.png",
    },
    {
        id:"6",
        nom:"Oven Risotto Mushrooms",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:true,
        image:"assets/i6.png",
    },
    {
        id:"7",
        nom:"Chicken and Avocado Kale Salad",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:false,
        image:"assets/i7.png",
    },
    {
        id:"8",
        nom:"Tutti-Frutti Cookies",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:true,
        image:"assets/i8.png",
    },
    {
        id:"9",
        nom:"Stuffing Crumbs Pasta",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:false,
        image:"assets/i9.png",
    },
    {
        id:"10",
        nom:"Meat Balls",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:true,
        image:"assets/i10.png",
    },
    {
        id:"11",
        nom:"Peach Tarte",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:false,
        image:"assets/i11.png",
    },
    {
        id:"12",
        nom:"Putine",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:true,
        image:"assets/i12.png",
    },
    {
        id:"13",
        nom:"Lentil Lasagna",
        ingredients:['coffe','water'],
        instructions:"azertyuioooopqsdfghj",
        favorite:true,
        image:"assets/i13.png",
    },
 ]