 import {Food} from "./app/shared/models/Food";

 export const sample_foods: Food[] =[
    {
        id:"1",
        name:"Skillet Stuffed Shell",
        ingredient:['coffe','  water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:false,
        imageUrl:"assets/i1.png",
    },
    {
        id:"2",
        name:"Mustard Chicken",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:true,
        imageUrl:"assets/i2.png",
    },
    {
        id:"3",
        name:"Easy Chicken Al Pastor",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:true,
        imageUrl:"assets/i3.png",
    },
    {
        id:"4",
        name:"Galette des Rois",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:false,
        imageUrl:"assets/i4.png",
    },
    {
        id:"5",
        name:"Tiny Pasta Salad",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:true,
        imageUrl:"assets/i5.png",
    },
    {
        id:"6",
        name:"Oven Risotto Mushrooms",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:true,
        imageUrl:"assets/i6.png",
    },
    {
        id:"7",
        name:"Chicken and Avocado Kale Salad",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:false,
        imageUrl:"assets/i7.png",
    },
    {
        id:"8",
        name:"Tutti-Frutti Cookies",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:true,
        imageUrl:"assets/i8.png",
    },
    {
        id:"9",
        name:"Stuffing Crumbs Pasta",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:false,
        imageUrl:"assets/i9.png",
    },
    {
        id:"10",
        name:"Meat Balls",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:true,
        imageUrl:"assets/i10.png",
    },
    {
        id:"11",
        name:"Peach Tarte",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:false,
        imageUrl:"assets/i11.png",
    },
    {
        id:"12",
        name:"Putine",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:true,
        imageUrl:"assets/i12.png",
    },
    {
        id:"13",
        name:"Lentil Lasagna",
        ingredient:['coffe','water'],
        preparation:"azertyuioooopqsdfghj",
        favorite:true,
        imageUrl:"assets/i13.png",
    },
 ]